- name: Echo 
  hosts: all
  connection: ssh

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: Install something
    ansible.builtin.dnf:
      name: net-tools
      state: latest